"""One-time converter: docs/seo-content/09 Compliance/01 Legal/*/02 Content.md -> typed TS content.

Wording is copied exactly, [CONFIRM: ...] placeholders included (the page renders them as
"to confirm" boxes, and a page that still has any stays unpublished). Headings use "&".
"""
import glob, io, json, os, re, sys

sys.argv = ["x", "general"]
here = os.path.dirname(os.path.abspath(__file__))
src = io.open(os.path.join(here, "gen_services2.py"), encoding="utf-8").read()
ns = {}
exec(src.split("os.makedirs(OUT")[0], ns)
parse_blocks, amp, BUTTON, LINK, slugify, camel = ns["parse_blocks"], ns["amp"], ns["BUTTON"], ns["LINK"], ns["slugify"], ns["camel"]
js = lambda v: json.dumps(v, ensure_ascii=False)

ROOT = r"E:/Wordpress Project Backup/Amazing Smiles"
DOCS = ROOT + "/docs/seo-content/09 Compliance/01 Legal"
OUT = ROOT + "/src/content/pages/legal"
SITE = "https://www.amazingsmilesbydesign.com"
# Buttons whose target is a placeholder: "**[Button] Label** → `[CONFIRM: ...]`"
BUTTON_ANY = re.compile(r"^\*\*\[Button\] (.+?)\*\* → `(.+?)`$")


def split_title(h1):
    words = h1.split()
    cut = 1 if len(words) <= 2 else len(words) - 2
    return {"lead": " ".join(words[:cut]), "accent": " ".join(words[cut:])}


os.makedirs(OUT, exist_ok=True)
for f in sorted(glob.glob(DOCS + "/*/02 Content.md")):
    folder = os.path.basename(os.path.dirname(f))
    content = io.open(f, encoding="utf-8").read()
    handoff = io.open(os.path.join(os.path.dirname(f), "03 Developer Handoff.md"), encoding="utf-8").read()
    path = re.search(r"\*\*URL:\*\* `(.+?)`", content).group(1)
    title = re.search(r"\*\*Title tag:\*\* (.*)", content).group(1).strip()
    desc = re.search(r"\*\*Meta description:\*\* (.*)", content).group(1).strip()
    graph = json.loads(re.findall(r"```json\n(.*?)\n```", handoff, re.S)[0])["@graph"]
    crumbs = next(n for n in graph if n["@type"] == "BreadcrumbList")["itemListElement"]
    breadcrumb = [{"name": c["name"], "path": c["item"].replace(SITE, "")} for c in crumbs]

    chunks = [c.strip("\n") for c in re.split(r"\n---\n", content)]
    hero = next(c for c in chunks if c.startswith("## [HERO]")).splitlines()
    start = chunks.index(next(c for c in chunks if c.startswith("## [HERO]")))
    rest = chunks[start + 1 :]

    h1 = next(l[2:] for l in hero if l.startswith("# "))
    intro, lines, buttons = [], [], []
    for l in hero:
        if l.startswith("#") or not l.strip():
            continue
        m = BUTTON_ANY.match(l)
        if m:
            buttons.append({"label": m.group(1), "href": m.group(2)})
        elif l.startswith("**") and not intro:
            intro.append(l.strip())
        elif l.startswith("**"):
            lines.append(l.strip())
        else:
            intro.append(l.strip())

    sections, links = [], []
    for chunk in rest:
        ls = chunk.splitlines()
        if ls and ls[0].startswith("## "):
            h2 = ls[0][3:].strip()
            blocks = parse_blocks(ls[1:])
            sections.append({"id": slugify(h2) + "-title", "title": amp(h2), "blocks": blocks})
        else:
            links += [{"label": amp(m.group(1)), "href": m.group(2)} for m in (LINK.match(l) for l in ls) if m]

    data = {
        "meta": {"path": path, "title": title, "description": desc},
        "breadcrumb": breadcrumb,
        "hero": {"title": split_title(h1), "intro": intro, "lines": lines, "buttons": buttons},
        "sections": sections,
        "links": links,
    }
    placeholders = content.split("## [HERO]")[1].count("[CONFIRM")
    slug = path.strip("/")
    name = camel(slug)
    out = f'''import type {{ LegalPageContent }} from "@/content/legal-page";

/**
 * Verbatim from docs/seo-content/09 Compliance/01 Legal/{folder}/02 Content.md (Final v1).
 * Generated by a one-time converter; headings use "&" (client rule). [CONFIRM: ...] items are
 * kept as written: the practice must supply them before this page is published (handoff).
 */
export const {name}: LegalPageContent = {js(data)};
'''
    io.open(os.path.join(OUT, slug + ".ts"), "w", encoding="utf-8", newline="\n").write(out)
    print(slug.ljust(36), "placeholders:", placeholders, "| H1", data["hero"]["title"], "| crumb", breadcrumb[-1]["name"])
    print("     hero intro:", [i[:50] for i in intro], "lines:", [l[:40] for l in lines], "buttons:", buttons)
    for s in sections:
        print("    ", s["id"], [b["kind"] + (str(len(b["items"])) if "items" in b else "") for b in s["blocks"]])
    print("     links:", links)
