/* Generated by tools/convert_blog.py from the old site mirror (copy of the live site, 2026-10-06). Do not edit by hand. */
import type { BlogPost } from "./types";

export const posts: BlogPost[] = [
  {
    "slug": "welcome-to-your-dentist-in-yardley",
    "title": "Welcome to Your Dentist in Yardley",
    "topic": "start",
    "date": "2025-12-06T02:24:01",
    "excerpt": "Here at Radiant Smiles, we understand the importance of having a dental practice that provides you with exceptional care.",
    "description": "Here at Radiant Smiles, we understand the importance of having a dental practice that provides you with exceptional care.",
    "blocks": [
      {
        "h2": "Dentist in Yardley"
      },
      {
        "p": "Here at Radiant Smiles, we understand the importance of having a dental practice that provides you with exceptional care. Our staff is committed to serving each and every patient with attentive care and quality dental work."
      },
      {
        "p": "Our practice provides general dentistry services including the prevention, diagnosis, and treatment of a wide variety of conditions and diseases that affect your teeth, gums, and oral health."
      },
      {
        "h2": "Our Practice’s Mission:"
      },
      {
        "p": "To fulfill our mission of providing quality dental care to you and your family, we are committed to:"
      },
      {
        "ul": [
          "Staying up to date with latest techniques and equipment.",
          "Ensuring a comfortable, relaxing environment.",
          "Exceeding your expectations with our professionalism."
        ]
      },
      {
        "h2": "We Are Committed to Your Oral Health"
      },
      {
        "p": "We are committed to ensuring your oral health is in excellent condition. We make this possible by attending to all dental issues, existing and potential, during your visit. **Call today [215-860-4600](tel:+12158604600)**."
      }
    ]
  },
  {
    "slug": "what-to-expect-with-teeth-whitening-in-yardley",
    "title": "What to Expect with Teeth Whitening in Yardley",
    "topic": "cosmetic",
    "date": "2025-12-06T02:23:12",
    "excerpt": "Teeth whitening, or simply bleaching, is a straightforward, non-invasive dental solution for changing the color of natural tooth enamel, and to…",
    "description": "Teeth whitening, or simply bleaching, is a straightforward, non-invasive dental solution for changing the color of natural tooth enamel, and to enhance…",
    "blocks": [
      {
        "p": "Teeth whitening, or simply bleaching, is a straightforward, non-invasive dental solution for changing the color of natural tooth enamel, and to enhance the appearance of your smile."
      },
      {
        "p": "Getting whiter teeth is considered the most popular esthetic concern for most dental patients. Common reasons for teeth whitening include:"
      },
      {
        "ul": [
          "Normal wear of tooth enamel",
          "Excess fluoridation (fluorosis) during early tooth development",
          "Stained teeth due to smoking or medications like tetracycline",
          "Brown or yellow stained teeth"
        ]
      },
      {
        "p": "Generally, any patient above the age of 10 years can consider teeth whitening to enhance their smile and boost confidence. However, it is not recommended for patients with oral issues such as dental cracks, leaky fillings, or dental decay, because the whitening products may irritate the tooth nerve, resulting in discomfort or more damage. In addition, patients with short teeth or a gummy smile may not necessarily look better after bleaching because whiter teeth tend to accentuate a gummy smile."
      },
      {
        "h2": "Your Consultation"
      },
      {
        "p": "Before you decide to whiten your teeth, it is important that you get a proper dental examination that includes X-rays to help establish the cause of tooth discoloration. In some cases, staining can be an indication of dental disease that requires a different treatment. But for simple whitening, options include bleaching from inside the tooth, for a dead tooth that has root canal, or a single-tooth bleaching tray for a living tooth.Once the cause and extent of discoloration and staining is known, you and your dentist can explore the different whitening options that apply to your case."
      },
      {
        "p": "Teeth usually don’t get discolored uniformly. So your dentist will come up with an appropriate strategy to whiten each tooth sufficiently to give you a uniform smile. This means that you can also choose to whiten only one or two teeth, or more."
      },
      {
        "h2": "Final Note"
      },
      {
        "p": "Restorations like tooth-colored fillings, veneers, bonding, bridges, and crowns do not stain or lighten. So, bleaching has no effect on existing dental restorations. As such, you may need to replace pre-existing dental work to match the new tooth shade achieved in your natural teeth following whitening."
      },
      {
        "p": "Please visit your dentist to learn more about [teeth whitening](/cosmetic-dentistry/teeth-whitening/)."
      }
    ]
  },
  {
    "slug": "affordable-dentist-in-my-area-yardley",
    "title": "Affordable Dentist In My Area, Yardley",
    "topic": "start",
    "date": "2025-12-06T02:22:06",
    "excerpt": "Getting affordable dental care is important to help you save costs on taking care of your own dental health and oral hygiene.",
    "description": "Getting affordable dental care is important to help you save costs on taking care of your own dental health and oral hygiene.",
    "blocks": [
      {
        "p": "Getting affordable dental care is important to help you save costs on taking care of your own dental health and oral hygiene. When looking for a dentist, consider our practice; we provide exceptional dental care and high-quality services without compromising either. Our experienced team is proud to serve you and your family, which can help you achieve a healthy smile at an affordable price."
      },
      {
        "h2": "Range of treatments"
      },
      {
        "p": "We provide a full range of dental care, including preventive appointments like routine teeth cleanings and hygiene, general family dental care, cosmetic dentistry to improve the look of your smile as well as restorative dentistry. This means that you can book your appointments at the same time to save on time and money that would be spent moving between different practices. That said, each treatment plan is individually tailored around every patient’s needs, so you receive the level of care that is best suited to your needs."
      },
      {
        "h2": "State-of-the-art dental equipment"
      },
      {
        "p": "Our investment in the newest dental equipment allows us to offer you innovative treatment options, and tailor a specialized plan just for your needs. We will not only identify looming dental problems early and introduce a simple solution, but also provide the complete treatment plan for major dental issues to restore your mouth’s function and appearance. For these reasons, our modern treatments are designed to be more comfortable and they focus on minimal intrusion yet maximum preservation for your natural teeth. This leads to faster healing, shorter recovery time, and long-lasting dental work."
      },
      {
        "h2": "Need an Affordable Dentist Near Me? Call Us Today"
      },
      {
        "p": "If you’re searching for an [affordable dentist](/family-dentistry/) who will not only offer reliable, high-quality care but also manage to keep your smile bright and healthy, then call our office today. We offer affordable, reliable, and highly professional dental services. From dental exams to routine teeth cleanings, teeth whitening, and other dental procedures, we offer quality treatments at an affordable price."
      },
      {
        "p": "Call our office today to discuss possible payment plans and financing options."
      }
    ]
  },
  {
    "slug": "affordable-toothache-relief-treatment-near-me-yardley",
    "title": "Affordable Toothache Relief & Treatment Near Me, Yardley",
    "topic": "emergencies",
    "date": "2025-12-06T02:20:47",
    "excerpt": "Toothaches are usually the result of tooth trauma or a dental condition, such as a cracked tooth, dental cavity, advanced gum disease, an exposed…",
    "description": "Toothaches are usually the result of tooth trauma or a dental condition, such as a cracked tooth, dental cavity, advanced gum disease, an exposed tooth…",
    "blocks": [
      {
        "p": "Toothaches are usually the result of tooth trauma or a dental condition, such as a cracked tooth, dental cavity, advanced gum disease, an exposed tooth root, or disorders of the jaw joint (temporomandibular joint). Pain can be either mild, severe or somewhere in-between, and it can vary from periodic to chronic."
      },
      {
        "h2": "Causes of tooth pain"
      },
      {
        "p": "The most common cause of dental pain is tooth decay, or cavities. Cavities are holes that form in the two outer layers of a tooth (tooth enamel and dentin) when you don’t brush your teeth properly, allowing acid in the mouth to erode them. If cavities are small in size, they may not cause any pain. However, as the cavity gets larger and deeper into the inner living tooth tissue (pulp), severe pain is felt when anything cold, hot, or sweet comes in contact with it."
      },
      {
        "p": "Other causes of tooth pain include:"
      },
      {
        "ul": [
          "Dental abscess – a tooth with a severe pulp injury can have an especially high risk of infection.",
          "Periodontal disease – bone loss and formation of deep gum pockets that cause gum infection and pain",
          "Tooth root sensitivities",
          "Impacted tooth",
          "Temporomandibular joint (TMJ) disorders – caused by arthritis, jaw injury from impact or recent dental work, or jaw muscle fatigue from habitually clenching and grinding teeth"
        ]
      },
      {
        "h2": "Treatment for tooth pain"
      },
      {
        "p": "Depending on the diagnosis, your dentist may recommend one or more of the following treatments for a toothache:"
      },
      {
        "ul": [
          "Over-the-counter pain relief medication",
          "Extraction of an impacted tooth",
          "Topical fluoride application for minor tooth sensitivities",
          "Dental filling for small and shallow cavities",
          "Dental crown for larger cavities",
          "Root canal therapy for cases that involve an injured pulp or infection,",
          "Tooth extraction of infected tooth followed by tooth replacement",
          "Teeth with advanced gum disease will need a thorough cleaning, as well as scaling and root planing in addition to improved tooth care habits."
        ]
      },
      {
        "p": "The most important step is to visit a dentist for an [examination](/preventative-care/teeth-cleaning-and-check-ups/)of the mouth and teeth. An appropriate treatment may be suggested from that point."
      }
    ]
  },
  {
    "slug": "general-dental-care-near-me-in-yardley",
    "title": "General Dental Care Near Me in Yardley",
    "topic": "checkups",
    "date": "2025-12-06T02:18:31",
    "excerpt": "When considering the foundation of a healthy lifestyle, dental care is paramount.",
    "description": "When considering the foundation of a healthy lifestyle, dental care is paramount.",
    "blocks": [
      {
        "p": "When considering the foundation of a healthy lifestyle, dental care is paramount. Gentle dental care treatments available near you, including check-ups, cleanings, dental crowns, and fillings, play a crucial role in not only maintaining oral hygiene but also in bolstering your overall health. Each of these treatments contributes to preventing and addressing potential oral health issues that, if left untreated, could lead to more significant health concerns."
      },
      {
        "h2": "General dental care treatments for your health"
      },
      {
        "ul": [
          "**Check-ups and Exams** Regular dental check-ups and thorough exams are the first line of defense against dental diseases. These appointments allow for the early detection of problems like cavities, gum disease, and even oral cancer, ensuring timely intervention and treatment.",
          "**Cleanings:** Professional cleanings go beyond what brushing and flossing can achieve at home. By removing plaque and tartar buildup, cleanings prevent the onset of gum disease and cavities, conditions linked to broader health issues such as heart disease and diabetes.",
          "**Dental Crowns:** Crowns restore the function and appearance of damaged teeth. By covering a tooth that has been decayed or broken, crowns prevent further damage and potential infections that can affect overall health.",
          "**Fillings:** Treating cavities with fillings immediately stops decay from spreading further. This not only saves the tooth but also prevents the spread of bacteria that can lead to more severe infections, protecting both oral and overall health."
        ]
      },
      {
        "p": "Understanding the importance of these treatments underscores the connection between oral health and general well-being. Implementing regular dental care routines significantly reduces the risk of developing conditions that can impact your body’s overall health, emphasizing the importance of oral hygiene in maintaining a healthy lifestyle."
      },
      {
        "p": "By opting for gentle dental care treatments near you, you’re taking a vital step towards enhancing your health. These treatments, designed with patient comfort and efficacy in mind, ensure that maintaining your oral health is a stress-free and beneficial process."
      },
      {
        "h2": "Begin Your Journey to Better Health"
      },
      {
        "p": "We’re committed to providing gentle and effective dental care that supports your overall health and well-being. With a comprehensive range of services tailored to meet your needs, our team is here to ensure that your dental care experience contributes positively to your health journey."
      },
      {
        "p": "If you’re ready to enhance your oral and overall health with gentle dental care treatments, contact us. Let us be your partner in achieving and maintaining optimal health through comprehensive and compassionate dental care."
      }
    ]
  },
  {
    "slug": "general-dental-exam-in-yardley",
    "title": "General Dental Exam in Yardley",
    "topic": "checkups",
    "date": "2025-12-06T02:17:40",
    "excerpt": "The cornerstone of maintaining a radiant and healthy smile lies in the thoroughness of dental exams.",
    "description": "The cornerstone of maintaining a radiant and healthy smile lies in the thoroughness of dental exams.",
    "blocks": [
      {
        "p": "The cornerstone of maintaining a radiant and healthy smile lies in the thoroughness of dental exams. These exams are not just a routine check-up; they are a comprehensive assessment that plays a crucial role in detecting, preventing, and treating dental issues before they escalate into more significant health concerns. Focusing in detail on the exam process can illuminate how this fundamental aspect of general dental care is instrumental in safeguarding not only your oral health but also enhancing your overall well-being."
      },
      {
        "h2": "The Process of a Dental Exam"
      },
      {
        "ul": [
          "**Medical History Review:** Understanding your overall health, medications, and any allergies to tailor the dental care to your specific needs.",
          "**Visual Inspection:** Using advanced tools and lighting to examine all surfaces of your teeth, the gums, and the mouth for signs of decay, gum disease, or other oral health issues.",
          "**X-rays:** Employing low-radiation digital X-rays to view beneath the surface of your gums and between teeth, identifying hidden problems such as impacted teeth, bone decay, cysts, tumors, and more.",
          "**Oral Cancer Screening:** Examining your lips, tongue, throat, tissues, and gums for any signs of oral cancer, a critical step given the increasing prevalence of the disease.",
          "**Evaluation of Existing Dental Work:** Checking fillings, crowns, bridges, and any other previous dental work to ensure they are in good condition and functioning properly.",
          "**Gum Health Assessment:** Measuring the depth of the spaces between your teeth and gums to detect any signs of gum disease, which can be an indicator of systemic health issues like diabetes and heart disease."
        ]
      },
      {
        "p": "Following the detailed exam, a personalized treatment plan is crafted to address any identified issues, incorporating treatments such as:"
      },
      {
        "ul": [
          "**Professional Cleanings:** To remove plaque and tartar buildup.",
          "**Dental Crowns:** To restore damaged teeth.",
          "**Cavity Fillings:** To repair teeth affected by decay."
        ]
      },
      {
        "p": "By focusing primarily on the comprehensive dental exam, patients can gain a deeper understanding of their oral health status and the proactive steps necessary to maintain or improve it. This detailed approach ensures that every aspect of your oral health is evaluated, forming the basis for any further treatments needed to enhance your smile and confidence."
      },
      {
        "h2": "Embrace Comprehensive Dental Care"
      },
      {
        "p": "We pride ourselves on offering detailed and comprehensive dental exams as the foundation of our general dental care treatments. Our dedication to thorough assessments ensures that we can provide personalized, effective care tailored to your unique needs."
      },
      {
        "p": "If you value a detailed approach to your dental health, contact us to schedule your next dental exam. Let us be your partner in achieving and maintaining optimal oral health, laying the groundwork for a brighter, healthier future."
      }
    ]
  },
  {
    "slug": "preventive-dental-treatments-near-me-in-yardley",
    "title": "Preventive Dental Treatments Near Me in Yardley",
    "topic": "checkups",
    "date": "2025-12-06T02:16:08",
    "excerpt": "A radiant smile is often the first thing noticed in social interactions, serving as a symbol of health, happiness, and confidence.",
    "description": "A radiant smile is often the first thing noticed in social interactions, serving as a symbol of health, happiness, and confidence.",
    "blocks": [
      {
        "p": "A radiant smile is often the first thing noticed in social interactions, serving as a symbol of health, happiness, and confidence. Achieving such a smile involves more than just daily brushing and flossing; it necessitates regular engagement with professional dental care. Routine dental care treatments open the door to a world where maintaining a dazzling smile and robust oral health is accessible and convenient. With an array of treatments designed to meet the needs of every family member, the path to a confident smile is just a step away."
      },
      {
        "h2": "Transforming smiles and confidence with routine care"
      },
      {
        "p": "The journey to a confident smile is paved with various routine dental treatments, each contributing to the overall aesthetics and health of your smile:"
      },
      {
        "ul": [
          "**Professional Cleaning:** Not only pivotal for dental health but also essential for maintaining a bright, stain-free smile, professional cleanings remove plaque and tartar that can dull your smile’s sparkle.",
          "**Oral Examinations:** By identifying potential issues like cavities or gum problems early, oral examinations ensure that any imperfections are addressed promptly, preserving the beauty and integrity of your smile.",
          "**Dental Hygiene:** Regular, effective brushing and flossing are key to keeping your teeth and gums healthy, directly contributing to a radiant, attractive smile that you’ll be proud to show off.",
          "**Fillings:** Beyond their primary function of treating cavities, fillings restore the smooth, uniform appearance of your teeth, using materials that match your natural tooth color for an undetectable, flawless finish.",
          "**Dental Crowns:** Crowns not only restore the function and strength of damaged teeth but also offer a cosmetic solution, enhancing the appearance of your teeth for a seamless, beautiful smile."
        ]
      },
      {
        "p": "By incorporating these treatments into your routine dental care, you not only maintain your oral health but also boost your confidence through a more attractive smile."
      },
      {
        "h2": "The impact of a confident smile"
      },
      {
        "p": "The benefits of a healthy, beautiful smile extend far beyond the physical. A confident smile can have a profound impact on various aspects of life:"
      },
      {
        "ul": [
          "**Enhanced Social Interactions:** A bright smile can make you more approachable and improve your social connections.",
          "**Increased Self-esteem:** Feeling good about your smile boosts overall confidence, positively affecting self-perception.",
          "**Professional Success:** A confident smile can contribute to a positive professional image, potentially opening doors to new opportunities."
        ]
      },
      {
        "p": "Investing in routine dental care is an investment in your overall quality of life, offering benefits that ripple through your personal, social, and professional worlds."
      },
      {
        "h2": "Your local partner in routine dental treatments"
      },
      {
        "p": "For those exploring “Routine Dental Care Treatments Near Me” we are your dedicated partner in achieving and maintaining the radiant smile you deserve. Our practice offers a welcoming environment where your dental health and confidence are our top priorities."
      },
      {
        "p": "If enhancing your smile and confidence is your goal, reach out to us. Our team is ready to support your journey with personalized care and state-of-the-art treatments, ensuring that every visit moves you closer to the smile of your dreams."
      }
    ]
  },
  {
    "slug": "natural-looking-dental-crowns-in-yardley",
    "title": "Natural Looking Dental Crowns in Yardley",
    "topic": "implants",
    "date": "2025-12-06T02:12:29",
    "excerpt": "A dental crown refers to a cap that is bonded over the entire surface of a damaged tooth to encapsulate the portion of the tooth above the gums.",
    "description": "A dental crown refers to a cap that is bonded over the entire surface of a damaged tooth to encapsulate the portion of the tooth above the gums.",
    "blocks": [
      {
        "p": "A dental crown refers to a cap that is bonded over the entire surface of a damaged tooth to encapsulate the portion of the tooth above the gums. It can be used to repair different types of tooth damage including cracked teeth, large cavities, discoloration, and misshapen teeth. They can also be used alongside other tooth restoration procedures such as root canal therapy, to strengthen the tooth, and dental bridgework to support a tooth replacement."
      },
      {
        "p": "A cap helps to restore the size, shape, and strength of a tooth while improving its appearance. If you’re a suitable candidate for dental crowns, your dentist may recommend one of the following materials for your permanent crown:"
      },
      {
        "h2": "Tooth-Colored Crowns"
      },
      {
        "p": "Tooth-colored crowns that are fabricated entirely from porcelain are referred to as all-porcelain crowns, while those made entirely from ceramic are known as all-ceramic crowns. Dental composite resin is another tooth-colored material that can give you an aesthetic restoration. Composite crowns are highly affordable, but are arguably the weakest material for crowns since they’re prone to chipping, cracking, and rapid wear."
      },
      {
        "p": "Your dentist may also recommend Zirconium, which is a fairly new dental material that produces crowns that are as strong and durable as metal crowns and natural-looking for an aesthetic restoration. They’re also biocompatible, meaning that they won’t cause allergic reactions, and can be fabricated at the dentist’s office for same-day crown restorations."
      },
      {
        "p": "Porcelain-fused-to-metal crowns are generally fabricated with a metal base and porcelain coating, which gives them the strength of metal crowns and the aesthetics of tooth-colored crowns. However, porcelain-metal crowns tend to be abrasive to opposing teeth, which increases their wear rate. The metal ring on the crown may also become visible in the event of gum recession."
      },
      {
        "h2": "Metal Crowns"
      },
      {
        "p": "Crowns made from metal are the strongest and most durable option, plus they’re not abrasive to opposing teeth. Different metals can be used to fabricate crowns, including gold, platinum, copper, and alloys like nickel-chromium and cobalt-chromium. Most metal crowns are made from a blend of metals, like gold and the base metal alloys."
      },
      {
        "h2": "Tooth-Colored vs. Metal Crowns"
      },
      {
        "p": "Tooth-colored materials give the restoration a natural look, which makes them a popular choice for repairing front teeth in order to preserve the aesthetics of your smile. They come in different shades, so you can choose a specific color that closely matches the shade of your teeth to make the restoration unnoticeable."
      },
      {
        "p": "Metal crowns are primarily used to repair back teeth because they’re strong and highly resistant, and they’re not visible when smiling, which makes aesthetics less of a concern. But they may not be suitable for people who’re allergic to metals or those with aesthetic concerns."
      },
      {
        "p": "To learn more about [Dental Crowns in Yardley](/restorative-dentistry/dental-crowns/) please contact us today."
      }
    ]
  },
  {
    "slug": "dental-implants-associated-costs-in-yardley",
    "title": "Dental Implant Costs in Yardley",
    "topic": "implants",
    "date": "2025-12-06T02:10:48",
    "excerpt": "Many dental professionals today consider dental implants as the standard of care for tooth replacement.",
    "description": "Many dental professionals today consider dental implants as the standard of care for tooth replacement.",
    "blocks": [
      {
        "p": "Many dental professionals today consider dental implants as the standard of care for tooth replacement. Yet, most dental insurance products do not cover the entire cost of dental implant placement because they consider dental implants as an elective procedure. That said, your insurance provider can cover the cost of getting a replacement crown depending on the material you choose for fabrication."
      },
      {
        "p": "During your consultation, your dental team will discuss with you the expected treatment plan and total cost of getting dental implants. Generally, there is a variety in the price range for a single dental implant. The actual amount depends on:"
      },
      {
        "ul": [
          "The position of the implant site in the mouth",
          "Experience of the oral surgeon performing the procedure",
          "The location of the dental practice",
          "Cost of the replacement crown",
          "Complexity of your case – affects cost of dental services and dental materials consumed"
        ]
      },
      {
        "h2": "Costs Associated with Complex Dental Implants"
      },
      {
        "p": "The standard procedure for performing a dental implant includes:"
      },
      {
        "ul": [
          "Tooth or teeth removal and site preparation before placing the dental implant.",
          "Implant placement – A dental implant (titanium post) is placed into the bone using a special drill and tools. The surgeon will then place a “healing cap” over the implant before stitching up the gum.",
          "Monitoring visits – You will have to wait for 2-6 months for the site to heal and the implant to integrate with the bone tissue. A temporary denture will be placed at the site for aesthetic purposes. You will need to visit your oral surgeon or dentist to track your recovery and make sure that there is no infection.",
          "Abutment placement – After successful integration of the implant to the bone, an abutment will be connected to the implant using a screw. Then an impression of the abutment is taken and sent to the dental lab to fabricate your custom crown.",
          "Tooth replacement – When the crown is ready, it will be secured to the abutment by cementing or with a screw."
        ]
      },
      {
        "p": "But if the implant site has signs of bone loss after tooth extraction, your oral surgeon may recommend bone grafting or sinus augmentation to build up the bone tissue and achieve a solid base to support the implant. This takes 2-6 months to heal before you can proceed with implant placement. During this time, you will need to make regular dental visits for tracking your healing."
      },
      {
        "h2": "Get Dental Implants Today"
      },
      {
        "p": "Although dental implants are expensive, and the treatment takes several months before you can start enjoying your investment, the final result is extremely satisfying. Dental implants look, feel, and function like your natural teeth, and after treatment, you won’t need to see your dentist for follow-up visits, except for routine professional cleaning."
      },
      {
        "p": "For more information on [dental implants in Yardley](/restorative-dentistry/dental-implants/) and to find out the cost of your individual treatment, please contact us today."
      }
    ]
  },
  {
    "slug": "best-candidate-for-dental-implants-in-yardley",
    "title": "Candidates for Dental Implants in Yardley",
    "topic": "implants",
    "date": "2025-12-06T02:06:58",
    "excerpt": "Dental implants refer to a biocompatible fixture that is surgically placed into the jawbone underneath an area with missing teeth, so it can fuse…",
    "description": "Dental implants refer to a biocompatible fixture that is surgically placed into the jawbone underneath an area with missing teeth, so it can fuse with the…",
    "blocks": [
      {
        "p": "Dental implants refer to a biocompatible fixture that is surgically placed into the jawbone underneath an area with missing teeth, so it can fuse with the bone to provide a strong and sturdy artificial tooth root that can support the replacement tooth. Your dentist may recommend dental implant placement for a replacement tooth in order to:"
      },
      {
        "ul": [
          "Prevent the teeth adjacent to the gap from tilting or shifting, which may misalign your bite and cause other problems",
          "Prevent teeth on the opposing jaw from growing irregularly because there’s no mate to make contact with, which may cause you to injure the gum tissue in that area. This can create a chronic sore spot and discomfort every time you bite",
          "Prevent the bone tissue under the gums from shrinking away (resorption) due to lack of stimulation during chewing, causing your face to appear aged"
        ]
      },
      {
        "h2": "Benefits of Dental Implants"
      },
      {
        "p": "Dental implants offer many benefits compared to the alternatives such as dentures and bridgework, including:"
      },
      {
        "ul": [
          "No allergic reactions – The implant is made from biocompatible materials like titanium",
          "Highly successful – Dental implants surgical placement has a success rate of over 98%",
          "Conservative restoration – Dental implants stand on their own without depending on the support of surrounding natural teeth",
          "Natural look and feel – Since implants integrate to the underlying bone tissue, they are so stable that they look and feel like your natural teeth.",
          "No changes to your lifestyle – You can continue to eat your favorite foods without any worry and practice your usual oral care routine."
        ]
      },
      {
        "p": "If you’re considering getting a dental implant, you should visit your dentist to find out whether you’re a suitable candidate for the treatment. This will depend on the position of the missing tooth in your mouth; the quality and quantity of jawbone in the area with the gap; and your general health. But most adults can successfully get implants if the necessary preparations are made through additional dental procedures and/or a change in your lifestyle habits."
      },
      {
        "p": "Please visit your dentist to learn more about [dental implants in Yardley](/restorative-dentistry/dental-implants/) and how they can help to restore the function and aesthetic of your mouth."
      }
    ]
  }
];
